[build]
  base = "flutterwave"
  command = "npm install"
  publish = "netlify"

[functions]
  directory = "netlify/functions"

[edge_functions]
  directory = "netlify/edge-functions"

[[edge_functions]]
  path = "/api/virtual-account"
  function = "create-virtual-account"
  cache = "manual"
  onError = "/error" 
