[build]
  command = "npm install"
  publish = "public"

[functions]
  directory = "netlify/functions"

[edge_functions]
  directory = "netlify/edge-functions"

[[edge_functions]]
  path = "/api/virtual-account"
  function = "create-virtual-account" 