[build]
  base = "flutterwave"
  command = "npm install"
  publish = "netlify"
  edge_functions = "netlify/edge-functions"

[functions]
  directory = "netlify/functions"

# 👇 Edge function definition
[[edge_functions]]
  function = "create-virtual-account"
  path = "/api/virtual-account"
